# **Instituto Tecnológico Vale**

## **Elementos de Automação e Programação para Automação**

### **Introdução a biblioteca Numpy**

### **Professor: André Almeida Santos**

### **Usando Numpy**

Numpy é a biblioteca central para computação científica em Python. Ela fornece um objeto de matriz multidimensional de alto desempenho e ferramentas para trabalhar com essas matrizes.

Ela também tem funções para trabalhar no domínio da álgebra linear, e transformada de Fourier.

Em Python, temos listas que servem ao propósito de matrizes, mas são lentas para processar.

NumPy visa fornecer um objeto de matriz que é até 50x mais rápido do que as listas Python tradicionais.

O objeto array em NumPy é chamado ndarray, ele fornece várias funções de suporte que tornam o trabalho com ndarray muito fácil.

Os arrays são usados com muita frequência em ciência de dados, onde velocidade e recursos são muito importantes.

Verifique a [documentação](https://numpy.org/doc/stable/user/quickstart.html) do numpy para mais informações.

Para usar o Numpy, primeiro precisamos importar o pacote numpy:

In [ ]:
import numpy as np

In [ ]:
# Verificando a versao do numpy instalada no colab

print(np.__version__)

**Criando um objeto NumPy ndarray**

NumPy é usado para trabalhar com matrizes. O objeto de matriz em NumPy é denominado ndarray.

Podemos criar um objeto ndarray NumPy usando a função array().

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

#### **Dimensões em arrays**

Uma dimensão em array é um nível de profundidade de array (arrays aninhadas).

**0-D Arrays**

São os números escalares

In [ ]:
arr = np.array(42)

print(arr)

**1-D Arrays**

É um vetor

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

**2-D Arrays**

É uma matriz

In [ ]:
# Observe como os colchetes são usados para indicar as dimensões

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

**3-D arrays**

É um 'cubo', ou seja, vária matrizes de mesma dimensão empilhadas.

A partir de três dimensões os arrays também são chamados de tensores.

In [ ]:
# Observe como os colchetes são usados para indicar as dimensões

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

![im](https://pbs.twimg.com/media/DZfhby-VQAA07ql.jpg)

NumPy Arrays fornece o atributo ndim que retorna um inteiro que nos diz quantas dimensões a matriz tem.

In [ ]:
arr_0d = np.array(42)
arr_1d = np.array([1, 2, 3, 4, 5])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

Você pode acessar um elemento da matriz referindo-se ao seu número de índice.

In [ ]:
print(arr_1d[0])

In [ ]:
print(arr_2d[0, 2])

In [ ]:
print(arr_3d[1, 1 ,2])

Fatiamento com numpy é igual ao fatiamento da lista: [start:end:step]

In [ ]:
print(arr_1d[1:])

In [ ]:
print(arr_2d[:2, :2])

In [ ]:
print(arr_3d[:, :2, :2])

**Forma do array**

A forma de uma matriz é o número de elementos em cada dimensão.

A função shape() nos permite verificar o formato so array.

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

In [ ]:
# Criando um array e definindo a dimensão na chamada da construção

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

O Numpy também oferece muitas funções para criar matrizes:

In [ ]:
a = np.zeros((2,2))  # Criar um array contendo só zeros
print(a)

In [ ]:
b = np.ones((1,2))   # Criar um array contendo só uns
print(b)

In [ ]:
c = np.full((2,2), 7) # Criar um array com constantes
print(c)

In [ ]:
d = np.eye(2)        # Criar uma matriz identidade 2x2
print(d)

In [ ]:
e = np.random.random((2,2)) # Criar uma matriz com valores aleatorios
print(e)

**Datatypes**


Cada matriz numpy é uma grade de elementos do mesmo tipo. Numpy fornece um grande conjunto de tipos de dados numéricos que você pode usar para construir matrizes. O Numpy tenta adivinhar um tipo de dados quando você cria uma matriz, mas as funções que constroem matrizes geralmente também incluem um argumento opcional para especificar explicitamente o tipo de dados. Aqui está um exemplo:

In [ ]:
x = np.array([1, 2])  # Deixe numpy escolher o tipo de dados
y = np.array([1.0, 2.0])  # Deixe numpy escolher o tipo de dados
z = np.array([1, 2], dtype=np.int64)  # Forçar um tipo de dados em particular

print(x.dtype, y.dtype, z.dtype)

**Array math**

Funções matemáticas básicas operam elemento a elemento em matrizes e estão disponíveis como sobrecargas de operador e como funções no módulo numpy:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print('')
print(y)

In [ ]:
# Soma elemento a elemento; ambos produzem a matriz
print(x + y)
print('')
print(np.add(x, y))

In [ ]:
# Substração elemento a elemento; ambos produzem a matriz
print(x - y)
print('')
print(np.subtract(x, y))

In [ ]:
# Multiplicação elemento a elemento; ambos produzem a matriz
print(x * y)
print('')
print(np.multiply(x, y))

In [ ]:
# Divisão elemento a elemento; ambos produzem a matriz
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print('')
print(np.divide(x, y))

In [ ]:
# Raiz quadrada elemento a elemento; ambos produzem a matriz
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

Observe que, ao contrário do MATLAB, * é a multiplicação elementar, não a multiplicação de matriz. Em vez disso, usamos a função de dot para calcular produtos internos de vetores, para multiplicar um vetor por uma matriz e para multiplicar matrizes. dot está disponível como uma função no módulo numpy e como um método de instância de objetos de matriz:

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Produto interno de vetores; ambos produzem 219
print(v.dot(w))
print('')
print(np.dot(v, w))

Você também pode usar o operador @ que é equivalente ao operador dot de numpy.

In [ ]:
print(v @ w)

In [ ]:

# Produto matricial / vetorial; ambos produzem a matriz de rank 1 [29 67]
print(x.dot(v))
print('')
print(np.dot(x, v))
#print(x @ v)

In [ ]:
# Matriz / produto da matriz; ambos produzem a matriz de rank 2
# [[19 22]
#  [43 50]]
print(x.dot(y))
print('')
print(np.dot(x, y))
#print(x @ y)

Numpy tem muitas funções úteis para realizar computações em arrays, um dos mais usados é o sum:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Calcule a soma de todos os elementos; imprime "10"
print(np.sum(x, axis=0))  # Calcule a soma de cada coluna; imprime "[4 6]"
print(np.sum(x, axis=1))  # Calcule a soma de cada linha; imprime "[3 7]"

Você pode encontrar a lista completa de funções matemáticas fornecidas por numpy na [documentação](https://numpy.org/doc/stable/reference/routines.math.html).

Além de computar funções matemáticas usando matrizes, frequentemente precisamos remodelar ou manipular dados em matrizes. O exemplo mais simples desse tipo de operação é a transposição de uma matriz; para transpor uma matriz, basta usar o atributo T de um objeto de matriz:

In [ ]:
print(x)
print('')
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v)
print('')
print("transpose\n", v.T)